### PR TITLE
Dynamic assets filenames for caching

### LINKED ISSUE #1120: Allow webpack dynamic assets filenames for caching
As defined [here](https://github.com/phenomic/phenomic/blob/c7bddecaa5cad5783569343f3b0692dddadc80cb/packages/plugin-renderer-react/src/server/renderHTML.js#L29), phenomic main script filename is hardcoded to the value specified in the configuration as `[config.bundleName].js` (default `phenomic.main.js`).

In the actual state, we can't use something akin to this in a custom webpack config, where the generated filename is dynamic in production : 
```
output: {
      ...
      filename: process.env.NODE_ENV === "production"
        ? "[name].[chunkhash].js"
        : "[name].js"
    },
```

It would be very useful for leveraging long-term caching of static assets, such as the main phenomic script or stylesheet, etc..

### PR DESCRIPTION
**Pull request by medfreeman**
fixes #1120 

Here's a really rough PR implementing dynamic assets filenames, applied to phenomic main js script.
I'm slowly getting familiar with the inner workings of phenomic, so perhaps not optimal, or not taking into account broader considerations.

### CODE REVIEW

**Comment by MoOx** [comment]
Can you fix flow errors please?

**Comment by medfreeman** [comment]
sure, thanks

**Comment by medfreeman** [comment]
Tests are ok now, but github has network problems for the last hour, that cause yarn to fail on install.
When you have a moment please relaunch the build, since i can't do it myself.
Thanks !

**Comment by medfreeman** [comment]
✓

**Comment by MoOx** [comment]
Will review this soon. I am planning to review SSR/dev html wrapping and this for alpha 6

**Comment by MoOx** [comment]
Squashing in alpha 6 PR and going to fix thing there (as I made some change for Html component)

**Comment by MoOx** [comment]
Thanks for this! I might make some changes in #1138 but you will get the credits!

**Pull request merged**
