### PR TITLE
Tutorial document changes to 05.md section

### PR DESCRIPTION
**Pull request by nalanirojas25**

### CODE REVIEW

**Comment by MoOx** [comment]
@nalanirojas25 you see here

image

We don't see you (`@nalanirojas25`). I can totally merge this, but you profile won't be credited as it should. You should review your local git config (in ~/.gitconfig) & check the email/username. Be sure to have this email added to your github account so github can track down the fact that it's you.

**Comment by nalanirojas25** [comment]
Thats weird cause its presented with nalanirojas25 on my end. Can you send me a pic of the exact location where its not saying nalanirojas25, please?

**Comment by nalanirojas25** [comment]
I need help with this because I really don't know why its not showing up as nalanirojas25. 
These are the places I've looked to see if nalanirojas25 is the account that was used. 

This is in the github committed files: 
github commits

This is in the terminal: 
terminal
 
I don't know where else to look. Some guidance would be appreciated.

**Comment by MoOx** [comment]
To check the email used on your computer:

```
git config --global --includes --get user.email
```

(should print an email)

Now go to https://github.com/settings/emails
And check that this email is added to the list.

Alternatively, you can change the email used for the commits (email given by the git config command) by using [git commit --amend option](https://stackoverflow.com/questions/3042437/how-to-change-the-commit-author-for-one-specific-commit).

**Comment by nalanirojas25** [comment]
Okay I think I fixed it. If not, please let me know. 
Thank you for helping me out with this. I appreciate your patience and help :)

**Comment by MoOx** [comment]
It seems you didn't push your modifications. I can't see anything different from this history https://github.com/nalanirojas25/phenomic/commits/tutorial-document-changes

Can you do locally a `git log` and paste here at least recent commits so I can help you to see the current local state?

**Comment by nalanirojas25** [comment]
git log

**Comment by nalanirojas25** [comment]
I think I made some improvements. This first line in the git log was a commit I did just now. I don't see changes on github though. I'm still trying to figure this out. 

git log

**Comment by MoOx** [comment]
"Changes" are visible 

image

This will not affect all previous commits. 
One thing you could do is to do the following from your current branch

- `git rebase master -i` (interactive git rebase)
For all commits except the one at the top of the list change "pick" (in the beginning of the line) to "f" or "fixup" (this will squash each commits with the first one, having one commit for such a change is enough)
once the rebase is finished 
- `git commit --amend --author="Author Name <email@address.com>"` (replace with your info).
- `git push --force` to overwrite the entire existing history you previously pushed. PR will be adjusted automatically as soon as the branch is updated.

**Comment by nalanirojas25** [comment]
Did it work? It looks like it did! :)

**Comment by MoOx** [comment]
Yes you did!

**Pull request merged**
